1) Eigenvalues and Eigenvectors of an array

Eigenvalues and Eigenvectors works only on Square matrix. Eigenvectors are by definition nonzero. Eigenvalues may be equal to zero.

Syntex : # np.linalg.eig(arr)



In [40]:
import numpy as np 

In [41]:
arr = np.array([[1,2],[3,4]])
print('Original value',arr)

eigval,eigvec = np.linalg.eig(arr) 
print('Eigenvalues value',eigval)
print('Eigenvectors value',eigvec)


Original value [[1 2]
 [3 4]]
Eigenvalues value [-0.37228132  5.37228132]
Eigenvectors value [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


2) digitize() 

Return the indices of the bins to which each value in input array belongs.

Syntax : np.digitize(x, bins, right=True)

Can be used to find the range in the variable of the dataframe and count of the bins.More like non visualization of histogram.


In [42]:
arr2 = np.array([1, 2, 10.0, 12.4, 15.5, 16, 17, 20,25,100]) 
bins = np.array([0, 5, 10, 15, 20]) #Creating the array and the range of the bins
ditrue = np.digitize(arr2,bins,right=True)
difalse = np.digitize(arr2,bins,right=False)
print('Bins indices if right is true',ditrue)#keeps the value in previous bin if the starting range of the bin and value are same
print('Bins indices if right is false',difalse) # keeps the value in same bin if the starting range of the bin and value are same

Bins indices if right is true [1 1 2 3 4 4 4 4 5 5]
Bins indices if right is false [1 1 3 3 4 4 4 5 5 5]


3) Repeat()
Repeat the element in the array n nunber of time as mentioned

Syntex: np.repeat(a, repeats, axis=None) 

can be used to repeat the data in the CNN



In [43]:
repeatarray = np.array([[1,2],[3,4]])
repeat1= np.repeat(repeatarray,2)
repeat2= np.repeat(repeatarray,5, axis=1) #Axis 1 repeats the elements in the array
repeat3= np.repeat(repeatarray,5, axis=0) #Axis 0 repeats the array

print(repeat1)
print(repeat2)
print(repeat3)

[1 1 2 2 3 3 4 4]
[[1 1 1 1 1 2 2 2 2 2]
 [3 3 3 3 3 4 4 4 4 4]]
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]
 [3 4]
 [3 4]]


4) squeeze()

syntex = np.squeeze(a, axis=None)

Removes the single-dimensional entries from the shape of an array.

In [44]:
sqarr=np.array([[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]])
print(sqarr)
print(sqarr.shape)
squeeze = np.squeeze(sqarr)
print(squeeze)
print(squeeze.shape)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]]
(1, 3, 5)
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
(3, 5)


5) linspace()

Syntex = np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)

Creates evenly spaced array from the start ans stop

In [45]:
linsp = np.linspace(1,100,num=11,retstep=True)
print(linsp) #Array evenly spaced and increased by the step of 9.9 

(array([  1. ,  10.9,  20.8,  30.7,  40.6,  50.5,  60.4,  70.3,  80.2,
        90.1, 100. ]), 9.9)


6) clip()

syntex = np.clip()

Given the min and max, values outside the min and max are clipped to the interval edges.and the clipped element are refilled with the min and max.


In [46]:
cliparr = np.array([10,20,30,40,50,60,70,80,90,100]) #10 Element
np.clip(cliparr,30,55) #Out also 10 Element

array([30, 30, 30, 40, 50, 55, 55, 55, 55, 55])

7)extract()

syntex = np.extract()

Return the elements of an array that satisfy some conditions.

In [47]:
exarr = np.arange(15).reshape((3, 5))
condition = exarr * 3 > 30
print(condition)
print(exarr)
extractarray = np.extract(condition, exarr)
print('Elements which satisfies the condition in the array',extractarray)

[[False False False False False]
 [False False False False False]
 [False  True  True  True  True]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
Elements which satisfies the condition in the array [11 12 13 14]


8) Argpartition()

syntax = np.argpartition(a, kth, axis=-1, kind='introselect', order=None)

Perform an indirect partition along the given axis using the algorithm specified by the kind keyword. It returns an array of indices of the same shape as a that index data along the given axis in partitioned order.

In [48]:
argpar = np.array([[ 4, 1, 5], [1, 7, 0] ]) 
print (argpar)  
argpar1 = np.argpartition(argpar, 1, axis = 1) 
print ("Output of argpartition array indices :\n ", argpar1)

[[4 1 5]
 [1 7 0]]
Output of argpartition array indices :
  [[1 0 2]
 [2 0 1]]


9) setdiff1d()

syntex =  np.setdiff1d()

Function find the set difference of two arrays and return the unique values in arr1 that are not in arr2.


In [49]:
set1= np.array([1, 2, 3, 2, 4, 5, 6, 8, 9])
set2= np.array([3, 4, 5, 6])
uniqueset = np.setdiff1d(set1, set2)
print('Element which is not in the set2 array and unique value in set 1 array',uniqueset)

Element which is not in the set2 array and unique value in set 1 array [1 2 8 9]


10) itemsize 
Syntex = array.itemsize
Length of one array element in bytes.

In [50]:
itemsize_arr = np.array([1,2,3],dtype= np.float128)
print('Length of one element in the array',itemsize_arr.itemsize)

Length of one element in the array 16


11) hstack()

syntex = numpy.hstack()

Stack the arrays in sequence horizontally.

In [51]:
hst1=np.array([1,2,3,4,5,6])
hst2=np.array([7,8,9])
hst3= np.hstack((hst1, hst2))
print('stacked the both the array horizontally',hst3)
hst4 = np.array([[1],[2],[3]])
hst5 = np.array([[4],[5],[6]])
hst6 = np.hstack((hst4,hst5))
print('stacked the both the array horizontally',hst6)

stacked the both the array horizontally [1 2 3 4 5 6 7 8 9]
stacked the both the array horizontally [[1 4]
 [2 5]
 [3 6]]


12) vstack()

syntex = numpy.vstack()

Stack arrays in sequence vertically.

In [52]:
vst1 = np.array([1, 2, 3])
vst2 = np.array([2, 3, 4])
vst3 = np.vstack((vst1,vst2))
print('stacked the both the array vertically',vst3)
vst4 = np.array([[1],[2],[3]])
vst5 = np.array([[4],[5],[6]])
vst6 = np.vstack((vst4,vst5))
print('stacked the both the array vertically',vst6)

stacked the both the array vertically [[1 2 3]
 [2 3 4]]
stacked the both the array vertically [[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


13) hsplit()

syntex = np.hsplit(ary, indices_or_sections)

Split an array into multiple sub-arrays horizontally.

In [53]:
hsp = np.arange(24).reshape(6, 4)
print(hsp)
np.hsplit(hsp,4)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


[array([[ 0],
        [ 4],
        [ 8],
        [12],
        [16],
        [20]]), array([[ 1],
        [ 5],
        [ 9],
        [13],
        [17],
        [21]]), array([[ 2],
        [ 6],
        [10],
        [14],
        [18],
        [22]]), array([[ 3],
        [ 7],
        [11],
        [15],
        [19],
        [23]])]

14) vsplit

syntex = np.vspilt(arr,indices_or_sections)

Split an array into multiple sub-arrays vertically.

In [54]:
vsp = np.arange(24).reshape(6, 4)
print(vsp)
np.vsplit(vsp,3)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]), array([[16, 17, 18, 19],
        [20, 21, 22, 23]])]

15) View vs shallow copy

syntex = array.copy() and array.view()

The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view


In [55]:
view_copy = np.array([1, 2, 3, 4, 5]) 
copyarr = view_copy.copy()
viewarr = view_copy.view() 
view_copy[0] = 10
print('Original Array',view_copy)
print('Copy Array',copyarr) #changes on original array does not change it on the copy
print ('View Fucntion view the array with the lastest chages on the array',viewarr)

Original Array [10  2  3  4  5]
Copy Array [1 2 3 4 5]
View Fucntion view the array with the lastest chages on the array [10  2  3  4  5]


16) Deep Copy 

syntax = copy.deepcopy()

Any chages in the copy data will not refelect in the original data

In [56]:
import copy
deepco = np.array([1, 'm', [2, 3, 4]], dtype=object)
deepco1 = copy.deepcopy(deepco)
deepco1[2][0] = 10
print(deepco)
print(deepco1)

[1 'm' list([2, 3, 4])]
[1 'm' list([10, 3, 4])]


17)copy()

Syntax = np.copy()

Any changes on the copy data will refelect in the original data also


In [57]:
npcopy = np.array([1, 'm', [2, 3, 4]], dtype=object)
npcopy1 = np.copy(npcopy)
npcopy1[2][0] = 10
print(npcopy)
print(npcopy1)

[1 'm' list([10, 3, 4])]
[1 'm' list([10, 3, 4])]


18) meshgrid()

syntax = np.meshgrid(*xi, copy=True, sparse=False, indexing='xy')

Return coordinate matrices from coordinate vectors.

Make N-D coordinate arrays for vectorized evaluations of N-D scalar/vector fields over N-D grids, given one-dimensional coordinate arrays x1, x2,…, xn.

In [58]:
nx, ny = (3, 2)
x = np.linspace(0, 1, nx)
y = np.linspace(0, 1, ny)
xv, yv = np.meshgrid(x, y)
print(xv)
print(yv)
vv, yy = np.meshgrid(x, y, sparse=True)  # make sparse output arrays
print(vv)
print(yy)

[[0.  0.5 1. ]
 [0.  0.5 1. ]]
[[0. 0. 0.]
 [1. 1. 1.]]
[[0.  0.5 1. ]]
[[0.]
 [1.]]


19) swapaxes()

syntax = np.swapaxes(a, axis1, axis2)

Interchange two axes of an array.

In [59]:
swapax = np.array([[1,2,3]])
swapax1= np.swapaxes(swapax,0,1)
print(swapax1)

swapax2 = np.array([[[0,1],[2,3]],[[4,5],[6,7]]])
print(swapax2)
print()
swapax3 = np.swapaxes(swapax2,0,2)
print(swapax3)

[[1]
 [2]
 [3]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]

[[[0 4]
  [2 6]]

 [[1 5]
  [3 7]]]


20) column_stack()

syntax = np.column_stack()

Stack 1-D arrays as columns into a 2-D array.

Take a sequence of 1-D arrays and stack them as columns to make a single 2-D array. 2-D arrays are stacked as-is, just like with hstack. 1-D arrays are turned into 2-D columns first.

In [60]:
c_Stack = np.array((1,2,3))
c_Stack1 = np.array((2,3,4))
np.column_stack((c_Stack,c_Stack1))

array([[1, 2],
       [2, 3],
       [3, 4]])